### ISSUE TITLE
GPU运行问题

### ISSUE THREAD

**Issue by MrL-CV** [ArtyZe/yolo_quantization#2]
看到运行介绍部分好像只是在训练的时候启用了GPU，推理的时候能不能也使用GPU跑呢？C++版本的YOLOV3-tiny支持GPU推理吗？

**Comment by ArtyZe** [comment]
> 看到运行介绍部分好像只是在训练的时候启用了GPU，推理的时候能不能也使用GPU跑呢？C++版本的YOLOV3-tiny支持GPU推理吗？

我理解着其实应该问题不大，gemm部分可以用cublas，但是像其他的比如upsample那些的话要写定点的kernel函数。
另外一种思路就是转成tensorrt，可能效果会更好
