### ISSUE TITLE
BUG？不使用openblas推理30s！

### ISSUE THREAD

**Issue by Broad-sky** [ArtyZe/yolo_quantization#5]
在不使用openblas的前提下，推理速度却延时30S！
\yolo_quantization\test_image\000044.jpg: Predicted in 28.104000 seconds.

**Comment by ArtyZe** [comment]
兄弟，这是一个量化演示案例，也就是说，我这个只是演示如何训练时量化。如果真正要部署到特定硬件，需要自己去做对应的加速，你看ncnn就是用汇编去实现卷积


| |
高扬
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年3月13日 ***@***.***> 写道：

在不使用openblas的前提下，推理速度却延时30S！
\yolo_quantization\test_image\000044.jpg: Predicted in 28.104000 seconds.

**Comment by Broad-sky** [comment]
感谢回复，已经明白！
这两天拜读了一下您的源码，发现在伪量化fake_quant_with_min_max_channel函数中，需要计算量化范围[a;b]，按论文中的理解，a,b对权重而言不就是最大最小值统计么，对激活而言采用EMA获取。那么您实现的源码中       
float nudged_min = (quant_min_float - nudged_zero_point) * nudged_scale;  
float nudged_max = (quant_max_float - nudged_zero_point) * nudged_scale;  
这两句代码是计算a,b吗，如果是，为什么这么计算，请楼主释然！！

**Comment by Broad-sky** [comment]
> 兄弟，这是一个量化演示案例，也就是说，我这个只是演示如何训练时量化。如果真正要部署到特定硬件，需要自己去做对应的加速，你看ncnn就是用汇编去实现卷积 | | 高扬 | | ***@***.*** | 签名由网易邮箱大师定制 在2021年3月13日 ***@***.***> 写道： 在不使用openblas的前提下，推理速度却延时30S！ \yolo_quantization\test_image\000044.jpg: Predicted in 28.104000 seconds. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复，已经明白！
这两天拜读了一下您的源码，发现在伪量化fake_quant_with_min_max_channel函数中，需要计算量化范围[a;b]，按论文中的理解，a,b对权重而言不就是最大最小值统计么，对激活而言采用EMA获取。那么您实现的源码中
float nudged_min = (quant_min_float - nudged_zero_point) * nudged_scale;
float nudged_max = (quant_max_float - nudged_zero_point) * nudged_scale;
这两句代码是计算a,b吗，如果是，为什么这么计算，请楼主释然！！

**Comment by ArtyZe** [comment]
不是的，这里是计算a，b


你说的这里，只是为了能够避免反量化回去后越界的情况，这里是保险措施，去掉也没关系。
EMA说白了就是bn中rolling mean和rolling variance的计算方式，你看一下就明白了


| |
高扬
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年3月15日 ***@***.***> 写道：

感谢回复，已经明白！
这两天拜读了一下您的源码，发现在伪量化fake_quant_with_min_max_channel函数中，需要计算量化范围[a;b]，按论文中的理解，a,b对权重而言不就是最大最小值统计么，对激活而言采用EMA获取。那么您实现的源码中
float nudged_min = (quant_min_float - nudged_zero_point) * nudged_scale;
float nudged_max = (quant_max_float - nudged_zero_point) * nudged_scale;
这两句代码是计算a,b吗，如果是，为什么这么计算，请楼主释然！！

**Comment by Broad-sky** [comment]
> 不是的，这里是计算a，b 你说的这里，只是为了能够避免反量化回去后越界的情况，这里是保险措施，去掉也没关系。 EMA说白了就是bn中rolling mean和rolling variance的计算方式，你看一下就明白了 | | 高扬 | | ***@***.*** | 签名由网易邮箱大师定制 在2021年3月15日 ***@***.***> 写道： 感谢回复，已经明白！ 这两天拜读了一下您的源码，发现在伪量化fake_quant_with_min_max_channel函数中，需要计算量化范围[a;b]，按论文中的理解，a,b对权重而言不就是最大最小值统计么，对激活而言采用EMA获取。那么您实现的源码中 float nudged_min = (quant_min_float - nudged_zero_point) * nudged_scale; float nudged_max = (quant_max_float - nudged_zero_point) * nudged_scale; 这两句代码是计算a,b吗，如果是，为什么这么计算，请楼主释然！！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复！！
能给我释然一下论文中M=2^-n  * M 0这个公式吗，看了您的源码和您的极市博客，感觉理解还是有点云里雾里的。谢谢！

**Comment by Broad-sky** [comment]
> 不是的，这里是计算a，b 你说的这里，只是为了能够避免反量化回去后越界的情况，这里是保险措施，去掉也没关系。 EMA说白了就是bn中rolling mean和rolling variance的计算方式，你看一下就明白了 | | 高扬 | | ***@***.*** | 签名由网易邮箱大师定制 在2021年3月15日 ***@***.***> 写道： 感谢回复，已经明白！ 这两天拜读了一下您的源码，发现在伪量化fake_quant_with_min_max_channel函数中，需要计算量化范围[a;b]，按论文中的理解，a,b对权重而言不就是最大最小值统计么，对激活而言采用EMA获取。那么您实现的源码中 float nudged_min = (quant_min_float - nudged_zero_point) * nudged_scale; float nudged_max = (quant_max_float - nudged_zero_point) * nudged_scale; 这两句代码是计算a,b吗，如果是，为什么这么计算，请楼主释然！！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

源码中见到将M0 * 2^31，该过程为将浮点转为定点，round后，紧接着见您又乘上了2^-31，这一步是将定点又转为浮点了？
